/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.productcustomer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DeleteCustomer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteCustomer.class.getName());

    /**
     * Creates new form DeleteCustomer
     */
    public DeleteCustomer() {
        initComponents();
        txtName.setEditable(false);
rbMale.setEnabled(false);
rbFemale.setEnabled(false);
rbOther.setEnabled(false);
txtEmail.setEditable(false);
txtPhone.setEditable(false);
txtAddress.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        btnClearCustomerForm = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        rbOther = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        rbMale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtCustomerID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        btnClearCustomerForm.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnClearCustomerForm.setForeground(new java.awt.Color(204, 153, 0));
        btnClearCustomerForm.setText("Clear ");
        btnClearCustomerForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCustomerFormActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearCustomerForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        btnDeleteCustomer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDeleteCustomer.setForeground(new java.awt.Color(255, 51, 51));
        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.setToolTipText("");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 246, -1, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setToolTipText("Enter customer address");
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 233, 170, 49));

        txtPhone.setToolTipText("Enter Customer Phone Number");
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 193, 173, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 196, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 165, 99, -1));

        txtEmail.setToolTipText("Enter Customer Email");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 165, 173, -1));

        buttonGroup1.add(rbOther);
        rbOther.setText("Other");
        getContentPane().add(rbOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 131, -1, -1));

        buttonGroup1.add(rbFemale);
        rbFemale.setText("Female");
        getContentPane().add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 131, -1, -1));

        buttonGroup1.add(rbMale);
        rbMale.setText("Male");
        getContentPane().add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 131, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 125, 99, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 100, -1, -1));

        txtName.setToolTipText("Enter the Customer Name");
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 97, 173, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(51, 204, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 53, -1, -1));
        getContentPane().add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 55, 81, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Customer ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 56, 92, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, 377, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Delete Customer ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        new AdminHome().setVisible(true); // Open admin home
        this.dispose(); // Close the current UpdateCustomer window
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
try {
    int customerId = Integer.parseInt(txtCustomerID.getText().trim());
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this customer?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    Connection con = DatabaseConnection.getConnection();
    String sql = "DELETE FROM customers WHERE id = ?";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setInt(1, customerId);

    int result = pst.executeUpdate();
    if (result > 0) {
        JOptionPane.showMessageDialog(this, "🗑️ Customer deleted successfully.");
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "⚠️ Customer not found.");
    }

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "❌ Invalid Customer ID.");
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "❌ SQL Error: " + e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

    try {
        int customerId = Integer.parseInt(txtCustomerID.getText().trim());
        Connection con = DatabaseConnection.getConnection();

        String sql = "SELECT * FROM customers WHERE id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, customerId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            txtName.setText(rs.getString("name"));
            String gender = rs.getString("gender");
            if (gender.equalsIgnoreCase("Male")) rbMale.setSelected(true);
            else if (gender.equalsIgnoreCase("Female")) rbFemale.setSelected(true);
            else rbOther.setSelected(true);
            txtEmail.setText(rs.getString("email"));
            txtPhone.setText(rs.getString("phone"));
            txtAddress.setText(rs.getString("address"));
        } else {
            JOptionPane.showMessageDialog(this, "❌ Customer not found.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "❌ Invalid Customer ID.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "❌ SQL Error: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearCustomerFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCustomerFormActionPerformed

    clearForm();
}

private void clearForm() {
    txtCustomerID.setText("");
    txtName.setText("");
    buttonGroup1.clearSelection();
    txtEmail.setText("");
    txtPhone.setText("");
    txtAddress.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearCustomerFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeleteCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearCustomerForm;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JRadioButton rbOther;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
